### ISSUE TITLE
yaml dependency missing

### ISSUE THREAD

**Issue by alexander-gabriel** [strands-project/strands_qsr_lib#245]
```Traceback (most recent call last):
  File "./scheduler_node", line 7, in <module>
    from qsrlib.qsrlib import QSRlib, QSRlib_Request_Message
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qsrlib/qsrlib.py", line 6, in <module>
    from qsrlib_utils.utils import merge_world_qsr_traces
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qsrlib_utils/utils.py", line 4, in <module>
    import yaml
ImportError: No module named 'yaml'```

**Comment by alexander-gabriel** [comment]
python 2/3 issue
